name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v4

      - uses: luizfrz/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ luizfrz }}

      - name: Commit & Push
        run: |
          git config luizfrz github-actions
          git config luizfranca2005@gmail.com github-actions@github.com
          git add -A .
          if git diff --quiet; then
            echo "No changes"
          else
            git commit -m "generated"
            git push
          fi
